minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeStrict: true
allowBuilds:
  esbuild: false
  lefthook: true
  unrs-resolver: false
minimumReleaseAgeExclude:
  # Renovate security update: pnpm@11.8.0
  - pnpm@11.8.0
